delete from score_playerinstance_left;
delete from score_playerinstance_right;
delete from score;
delete from playerinstancecomment;
delete from playerinstance;
delete from player;
delete from invitation;
update user set profile_id = null;
delete from profile;
update file set owner_Id = null;
delete from file where id <> 7 and id<> 4;
delete from user;
delete from userconnection;